#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
figlet 'BOT TESTE' | boxes -d stone -p a0v0 | lolcat
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m           ATIVAR BOT TESTE SSH                    \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[0;31m║\033[0m"
    echo -e "\033[01;31m║\033[0m"
    echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;32mINGRESE SU TOKEN\033[1;37m: "
    read token
    clear
    echo ""
    echo -e "\033[1;32mINICIANDO BOT TESTE \033[0m\n"
    cd $HOME/BOT
    rm -rf $HOME/BOT/botssh
    wget https://github.com/netfreeplus/SSHPLUS2/raw/main/Sistema/botssh >/dev/null 2>&1
    chmod 777 botssh
    echo ""
    sleep 1
    screen -dmS bot_teste ./botssh $token > /dev/null 2>&1
    clear
    echo "BOT ACTIVADO"
    menu
} || {
    screen -r -S "bot_teste" -X quit
    clear
    echo "BOT DESACTIVADO"
    menu
}
